version: 1.0.{build}

init:
  # Set "build version number" to "short-commit-hash" or when tagged to "tag name" (Travis style)
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true")
      {
        Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_TAG_NAME.TrimStart("v"))"
      }
      else
      {
        Update-AppveyorBuild -Version "dev-$($env:APPVEYOR_REPO_COMMIT.substring(0,7))"
      }

build_script:
  - pushd DigTest & nuget restore & popd
  - '"C:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe" DigTest\DigTest.sln /p:Configuration=Release /fl /t:Rebuild /m'
  - python -m pip install requests==2.18.4
  - python Dig\tab-src\surrogate-modeling\build.py

test_script:
  - DigTest\bin\Release\DigTest.exe <nul

artifacts:
  - path: "*.log"
